<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\..\..\TL.Engine\Extensions</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>..\..\..\TL.Engine\Extensions</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Handlers\**" />
    <EmbeddedResource Remove="Handlers\**" />
    <None Remove="Handlers\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Telegram.Bot" Version="14.10.0" />
    <PackageReference Include="Telegram.Bot.Extensions.Passport" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Engine\TL.Engine.SDK\TL.Engine.SDK.csproj" />
  </ItemGroup>

</Project>
