// <auto-generated />
using System;
using ExtCore.Data.EntityFramework.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace TL.Engine.Migrations
{
    [DbContext(typeof(StorageContext))]
    [Migration("20190420000956_v1016")]
    partial class v1016
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TL.Account.Data.Entities.Relationships.Subscription", b =>
                {
                    b.Property<Guid>("FromId");

                    b.Property<Guid>("ToId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<bool>("Quiet");

                    b.HasKey("FromId", "ToId");

                    b.ToTable("AccountSubscriptions");

                    b.HasData(
                        new
                        {
                            FromId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            ToId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 4, 20, 0, 9, 52, 699, DateTimeKind.Utc).AddTicks(7536),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 4, 20, 0, 9, 52, 699, DateTimeKind.Utc).AddTicks(7558),
                            Quiet = false
                        },
                        new
                        {
                            FromId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            ToId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 4, 20, 0, 9, 52, 699, DateTimeKind.Utc).AddTicks(9817),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 4, 20, 0, 9, 52, 699, DateTimeKind.Utc).AddTicks(9824),
                            Quiet = false
                        });
                });

            modelBuilder.Entity("TL.Api.Data.Entities.Security.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<Guid?>("OwnerId");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("ApiTokens");
                });

            modelBuilder.Entity("TL.Api.Data.Entities.Security.TokenLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Method");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Parameters");

                    b.Property<int>("StatusCode");

                    b.Property<Guid>("TokenId");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("ApiTokensLogs");
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Reports.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Message");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<int?>("Priority");

                    b.Property<string>("StackTrace");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CreationDate");

                    b.HasIndex("Message");

                    b.HasIndex("ModifiedDate");

                    b.HasIndex("UserId");

                    b.ToTable("_Reports");
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Security.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("_Groups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 4, 20, 0, 9, 52, 683, DateTimeKind.Utc).AddTicks(9856),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 4, 20, 0, 9, 52, 683, DateTimeKind.Utc).AddTicks(9864),
                            Name = "sa"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreationDate = new DateTime(2019, 4, 20, 0, 9, 52, 683, DateTimeKind.Utc).AddTicks(9882),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 4, 20, 0, 9, 52, 683, DateTimeKind.Utc).AddTicks(9883),
                            Name = "all"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 4, 20, 0, 9, 52, 683, DateTimeKind.Utc).AddTicks(9891),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 4, 20, 0, 9, 52, 683, DateTimeKind.Utc).AddTicks(9892),
                            Name = "user"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 4, 20, 0, 9, 52, 683, DateTimeKind.Utc).AddTicks(9898),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 4, 20, 0, 9, 52, 683, DateTimeKind.Utc).AddTicks(9900),
                            Name = "system"
                        });
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Security.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("_Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 4, 20, 0, 9, 52, 682, DateTimeKind.Utc).AddTicks(4067),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 4, 20, 0, 9, 52, 682, DateTimeKind.Utc).AddTicks(4075),
                            Name = "sa"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 4, 20, 0, 9, 52, 682, DateTimeKind.Utc).AddTicks(4094),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 4, 20, 0, 9, 52, 682, DateTimeKind.Utc).AddTicks(4096),
                            Name = "user"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 4, 20, 0, 9, 52, 682, DateTimeKind.Utc).AddTicks(4103),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 4, 20, 0, 9, 52, 682, DateTimeKind.Utc).AddTicks(4105),
                            Name = "system"
                        });
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Security.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Description");

                    b.Property<bool>("IsClosed");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("_Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 4, 20, 0, 9, 52, 672, DateTimeKind.Utc).AddTicks(5714),
                            Description = "Супер-пользователь системы TL Engine",
                            IsClosed = false,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 4, 20, 0, 9, 52, 672, DateTimeKind.Utc).AddTicks(5736),
                            Username = "sa"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 4, 20, 0, 9, 52, 672, DateTimeKind.Utc).AddTicks(6781),
                            Description = "Шаблонный пользователь системы TL Engine",
                            IsClosed = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 4, 20, 0, 9, 52, 672, DateTimeKind.Utc).AddTicks(6791),
                            Username = "user"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 4, 20, 0, 9, 52, 672, DateTimeKind.Utc).AddTicks(6822),
                            Description = "Автоматика системы TL Engine",
                            IsClosed = true,
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 4, 20, 0, 9, 52, 672, DateTimeKind.Utc).AddTicks(6823),
                            Username = "system"
                        });
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Security.UserGroup", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("GroupId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("_UsersGroups");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            GroupId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreationDate = new DateTime(2019, 4, 20, 0, 9, 52, 679, DateTimeKind.Utc).AddTicks(6279),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 4, 20, 0, 9, 52, 679, DateTimeKind.Utc).AddTicks(6294)
                        },
                        new
                        {
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            GroupId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 4, 20, 0, 9, 52, 680, DateTimeKind.Utc).AddTicks(176),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 4, 20, 0, 9, 52, 680, DateTimeKind.Utc).AddTicks(183)
                        },
                        new
                        {
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            GroupId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 4, 20, 0, 9, 52, 680, DateTimeKind.Utc).AddTicks(1120),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 4, 20, 0, 9, 52, 680, DateTimeKind.Utc).AddTicks(1122)
                        },
                        new
                        {
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            GroupId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 4, 20, 0, 9, 52, 680, DateTimeKind.Utc).AddTicks(1981),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 4, 20, 0, 9, 52, 680, DateTimeKind.Utc).AddTicks(1982)
                        },
                        new
                        {
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            GroupId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreationDate = new DateTime(2019, 4, 20, 0, 9, 52, 680, DateTimeKind.Utc).AddTicks(4792),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 4, 20, 0, 9, 52, 680, DateTimeKind.Utc).AddTicks(4799)
                        },
                        new
                        {
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            GroupId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 4, 20, 0, 9, 52, 680, DateTimeKind.Utc).AddTicks(4848),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 4, 20, 0, 9, 52, 680, DateTimeKind.Utc).AddTicks(4849)
                        },
                        new
                        {
                            UserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            GroupId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreationDate = new DateTime(2019, 4, 20, 0, 9, 52, 680, DateTimeKind.Utc).AddTicks(7076),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 4, 20, 0, 9, 52, 680, DateTimeKind.Utc).AddTicks(7084)
                        },
                        new
                        {
                            UserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            GroupId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 4, 20, 0, 9, 52, 680, DateTimeKind.Utc).AddTicks(7118),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 4, 20, 0, 9, 52, 680, DateTimeKind.Utc).AddTicks(7119)
                        });
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Security.UserRole", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("_UsersRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            RoleId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 4, 20, 0, 9, 52, 676, DateTimeKind.Utc).AddTicks(46),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 4, 20, 0, 9, 52, 676, DateTimeKind.Utc).AddTicks(60)
                        },
                        new
                        {
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            RoleId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 4, 20, 0, 9, 52, 676, DateTimeKind.Utc).AddTicks(4150),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 4, 20, 0, 9, 52, 676, DateTimeKind.Utc).AddTicks(4158)
                        },
                        new
                        {
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            RoleId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 4, 20, 0, 9, 52, 676, DateTimeKind.Utc).AddTicks(5113),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 4, 20, 0, 9, 52, 676, DateTimeKind.Utc).AddTicks(5115)
                        },
                        new
                        {
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            RoleId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 4, 20, 0, 9, 52, 676, DateTimeKind.Utc).AddTicks(7105),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 4, 20, 0, 9, 52, 676, DateTimeKind.Utc).AddTicks(7112)
                        },
                        new
                        {
                            UserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            RoleId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 4, 20, 0, 9, 52, 676, DateTimeKind.Utc).AddTicks(8601),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 4, 20, 0, 9, 52, 676, DateTimeKind.Utc).AddTicks(8608)
                        });
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.System.StaticFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AuthorId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<byte[]>("Data");

                    b.Property<string>("DisplayName");

                    b.Property<string>("Extension");

                    b.Property<string>("FileName");

                    b.Property<string>("FullName");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LocalPath");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<Guid?>("OriginalId");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("OriginalId");

                    b.ToTable("_StaticFiles");
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.System.StringVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"));

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("Name");

                    b.ToTable("_StringVariables");
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.Relationships.TgConnection", b =>
                {
                    b.Property<Guid>("BotId");

                    b.Property<Guid>("UserId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("BotId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("IntegrationsTgConnections");
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.Security.TgRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("IntegrationsTgRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 4, 20, 0, 9, 52, 736, DateTimeKind.Utc).AddTicks(9218),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 4, 20, 0, 9, 52, 736, DateTimeKind.Utc).AddTicks(9239),
                            Name = "sa"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreationDate = new DateTime(2019, 4, 20, 0, 9, 52, 737, DateTimeKind.Utc).AddTicks(1750),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 4, 20, 0, 9, 52, 737, DateTimeKind.Utc).AddTicks(1760),
                            Name = "admin"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 4, 20, 0, 9, 52, 737, DateTimeKind.Utc).AddTicks(2674),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 4, 20, 0, 9, 52, 737, DateTimeKind.Utc).AddTicks(2682),
                            Name = "user"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 4, 20, 0, 9, 52, 737, DateTimeKind.Utc).AddTicks(3711),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 4, 20, 0, 9, 52, 737, DateTimeKind.Utc).AddTicks(3719),
                            Name = "system"
                        });
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.Security.TgUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<int>("TgId");

                    b.Property<Guid?>("UserId");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("IntegrationsTgUsers");
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.Security.TgUserRole", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("IntegrationsTgUsersRoles");
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.System.TgBot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AutoStart");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsRelevant");

                    b.Property<DateTime?>("LastStartDate");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("NativeName");

                    b.Property<bool>("SkipUpdates");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Token");

                    b.Property<string>("TypeName");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("Token", "TypeName")
                        .IsUnique()
                        .HasFilter("[Token] IS NOT NULL AND [TypeName] IS NOT NULL");

                    b.ToTable("IntegrationsTgBots");
                });

            modelBuilder.Entity("TL.Account.Data.Entities.Relationships.Subscription", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.User", "From")
                        .WithMany()
                        .HasForeignKey("FromId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TL.Api.Data.Entities.Security.Token", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");
                });

            modelBuilder.Entity("TL.Api.Data.Entities.Security.TokenLog", b =>
                {
                    b.HasOne("TL.Api.Data.Entities.Security.Token", "Token")
                        .WithMany("Logs")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Engine.Data.Entities.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Reports.Report", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Security.UserGroup", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Engine.Data.Entities.Security.User", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Security.UserRole", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Engine.Data.Entities.Security.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.System.StaticFile", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("TL.Engine.Data.Entities.System.StaticFile", "Original")
                        .WithMany("Duplicates")
                        .HasForeignKey("OriginalId");
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.System.StringVariable", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.Relationships.TgConnection", b =>
                {
                    b.HasOne("TL.Integrations.Data.Entities.Telegram.System.TgBot", "Bot")
                        .WithMany("Connections")
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Integrations.Data.Entities.Telegram.Security.TgUser", "User")
                        .WithMany("Connections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.Security.TgUser", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.Security.TgUserRole", b =>
                {
                    b.HasOne("TL.Integrations.Data.Entities.Telegram.Security.TgRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Integrations.Data.Entities.Telegram.Security.TgUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
