// <auto-generated />
using System;
using ExtCore.Data.EntityFramework.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace TL.Engine.Migrations
{
    [DbContext(typeof(StorageContext))]
    [Migration("20190717065004_v1106-4-2")]
    partial class v110642
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TL.Account.Data.Entities.Relationships.Subscription", b =>
                {
                    b.Property<Guid>("FromId");

                    b.Property<Guid>("ToId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<bool>("Quiet");

                    b.HasKey("FromId", "ToId");

                    b.ToTable("Account.Subscriptions");

                    b.HasData(
                        new
                        {
                            FromId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            ToId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 126, DateTimeKind.Utc).AddTicks(3745),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 126, DateTimeKind.Utc).AddTicks(3763),
                            Quiet = false
                        },
                        new
                        {
                            FromId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            ToId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 126, DateTimeKind.Utc).AddTicks(5523),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 126, DateTimeKind.Utc).AddTicks(5528),
                            Quiet = false
                        });
                });

            modelBuilder.Entity("TL.Api.Data.Entities.Security.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<Guid?>("OwnerId");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Api.Tokens");
                });

            modelBuilder.Entity("TL.Api.Data.Entities.Security.TokenLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Method");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Parameters");

                    b.Property<int>("StatusCode");

                    b.Property<Guid>("TokenId");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("Api.TokensLogs");
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Reports.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Message");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<int?>("Priority");

                    b.Property<string>("StackTrace");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CreationDate");

                    b.HasIndex("Message");

                    b.HasIndex("ModifiedDate");

                    b.HasIndex("UserId");

                    b.ToTable("_.Reports");
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Security.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("_.Groups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 96, DateTimeKind.Utc).AddTicks(3329),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 96, DateTimeKind.Utc).AddTicks(3339),
                            Name = "sa"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 96, DateTimeKind.Utc).AddTicks(3357),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 96, DateTimeKind.Utc).AddTicks(3358),
                            Name = "all"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 96, DateTimeKind.Utc).AddTicks(3365),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 96, DateTimeKind.Utc).AddTicks(3366),
                            Name = "user"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 96, DateTimeKind.Utc).AddTicks(3372),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 96, DateTimeKind.Utc).AddTicks(3373),
                            Name = "system"
                        });
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Security.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("_.Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 95, DateTimeKind.Utc).AddTicks(242),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 95, DateTimeKind.Utc).AddTicks(252),
                            Name = "sa"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 95, DateTimeKind.Utc).AddTicks(276),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 95, DateTimeKind.Utc).AddTicks(277),
                            Name = "user"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 95, DateTimeKind.Utc).AddTicks(284),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 95, DateTimeKind.Utc).AddTicks(285),
                            Name = "system"
                        });
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Security.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Description");

                    b.Property<bool>("IsClosed");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("LastActivity");

                    b.Property<DateTime>("LastLogon");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("Username");

                    b.Property<Guid>("WebTicket");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("_.Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 81, DateTimeKind.Utc).AddTicks(9368),
                            Description = "Супер-пользователь системы TL Engine",
                            IsClosed = false,
                            IsDeleted = false,
                            LastActivity = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastLogon = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 81, DateTimeKind.Utc).AddTicks(9385),
                            Username = "sa",
                            WebTicket = new Guid("9e91ecdb-241f-4f29-94fd-fcb801de27d9")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 82, DateTimeKind.Utc).AddTicks(210),
                            Description = "Шаблонный пользователь системы TL Engine",
                            IsClosed = true,
                            IsDeleted = false,
                            LastActivity = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastLogon = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 82, DateTimeKind.Utc).AddTicks(215),
                            Username = "user",
                            WebTicket = new Guid("03ca20ef-701b-4f57-a38d-9f7d41a8289b")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 82, DateTimeKind.Utc).AddTicks(238),
                            Description = "Автоматика системы TL Engine",
                            IsClosed = true,
                            IsDeleted = false,
                            LastActivity = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastLogon = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 82, DateTimeKind.Utc).AddTicks(240),
                            Username = "system",
                            WebTicket = new Guid("afb96b63-fa14-4bb8-b8b1-0f3106ec7c49")
                        });
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Security.UserGroup", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("GroupId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("_.UsersGroups");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            GroupId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 92, DateTimeKind.Utc).AddTicks(5181),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 92, DateTimeKind.Utc).AddTicks(5200)
                        },
                        new
                        {
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            GroupId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 92, DateTimeKind.Utc).AddTicks(8339),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 92, DateTimeKind.Utc).AddTicks(8344)
                        },
                        new
                        {
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            GroupId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 92, DateTimeKind.Utc).AddTicks(9067),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 92, DateTimeKind.Utc).AddTicks(9068)
                        },
                        new
                        {
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            GroupId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 92, DateTimeKind.Utc).AddTicks(9723),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 92, DateTimeKind.Utc).AddTicks(9724)
                        },
                        new
                        {
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            GroupId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 93, DateTimeKind.Utc).AddTicks(1987),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 93, DateTimeKind.Utc).AddTicks(1993)
                        },
                        new
                        {
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            GroupId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 93, DateTimeKind.Utc).AddTicks(2037),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 93, DateTimeKind.Utc).AddTicks(2038)
                        },
                        new
                        {
                            UserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            GroupId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 93, DateTimeKind.Utc).AddTicks(4072),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 93, DateTimeKind.Utc).AddTicks(4077)
                        },
                        new
                        {
                            UserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            GroupId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 93, DateTimeKind.Utc).AddTicks(4108),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 93, DateTimeKind.Utc).AddTicks(4109)
                        });
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Security.UserRole", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("_.UsersRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            RoleId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 88, DateTimeKind.Utc).AddTicks(9288),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 88, DateTimeKind.Utc).AddTicks(9303)
                        },
                        new
                        {
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            RoleId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 89, DateTimeKind.Utc).AddTicks(2322),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 89, DateTimeKind.Utc).AddTicks(2327)
                        },
                        new
                        {
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            RoleId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 89, DateTimeKind.Utc).AddTicks(3078),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 89, DateTimeKind.Utc).AddTicks(3079)
                        },
                        new
                        {
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            RoleId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 89, DateTimeKind.Utc).AddTicks(4627),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 89, DateTimeKind.Utc).AddTicks(4632)
                        },
                        new
                        {
                            UserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            RoleId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 89, DateTimeKind.Utc).AddTicks(5919),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 89, DateTimeKind.Utc).AddTicks(5925)
                        });
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.System.StaticFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AuthorId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<byte[]>("Data");

                    b.Property<string>("DisplayName");

                    b.Property<string>("Extension");

                    b.Property<string>("FileName");

                    b.Property<string>("FullName");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LocalPath");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<Guid?>("OriginalId");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("OriginalId");

                    b.ToTable("_.StaticFiles");
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.System.StringVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"));

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("Name");

                    b.ToTable("_.StringVariables");
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.Relationships.TgConnection", b =>
                {
                    b.Property<Guid>("BotId");

                    b.Property<Guid>("UserId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("BotId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Integrations.TgConnections");
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.Security.TgRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Integrations.TgRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 154, DateTimeKind.Utc).AddTicks(1722),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 154, DateTimeKind.Utc).AddTicks(1747),
                            Name = "sa"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 154, DateTimeKind.Utc).AddTicks(3902),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 154, DateTimeKind.Utc).AddTicks(3910),
                            Name = "admin"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 154, DateTimeKind.Utc).AddTicks(4593),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 154, DateTimeKind.Utc).AddTicks(4598),
                            Name = "user"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 154, DateTimeKind.Utc).AddTicks(5218),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 154, DateTimeKind.Utc).AddTicks(5222),
                            Name = "system"
                        });
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.Security.TgUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<int>("TgId");

                    b.Property<Guid?>("UserId");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Integrations.TgUsers");
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.Security.TgUserRole", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("Integrations.TgUsersRoles");
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.System.TgBot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AutoStart");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsRelevant");

                    b.Property<DateTime?>("LastStartDate");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("NativeName");

                    b.Property<bool>("SkipUpdates");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Token");

                    b.Property<string>("TypeName");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("Token", "TypeName")
                        .IsUnique()
                        .HasFilter("[Token] IS NOT NULL AND [TypeName] IS NOT NULL");

                    b.ToTable("Integrations.TgBots");
                });

            modelBuilder.Entity("TL.Linker.Data.Entities.Core.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<decimal>("Identifier")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("LifetimeSeconds")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(2147483647);

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasFilter("[Url] IS NOT NULL");

                    b.ToTable("Linker.Links");
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Core.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<Guid>("FileId");

                    b.Property<Guid?>("FolderId");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name");

                    b.Property<Guid>("OwnerId");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.HasIndex("FolderId");

                    b.HasIndex("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.ToTable("Registry.Files");
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Core.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name");

                    b.Property<Guid>("OwnerId");

                    b.Property<Guid?>("ParantId");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ParantId");

                    b.ToTable("Registry.Folders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 220, DateTimeKind.Utc).AddTicks(2545),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 220, DateTimeKind.Utc).AddTicks(2549),
                            Name = "System Root Registry Folder",
                            OwnerId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("ff44803e-e998-451f-8507-d1ecbfcbcf79"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 222, DateTimeKind.Utc).AddTicks(2552),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 222, DateTimeKind.Utc).AddTicks(2556),
                            Name = "Module Store Registry Folder",
                            OwnerId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            ParantId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        });
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Core.Registry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name");

                    b.Property<Guid>("OwnerId");

                    b.Property<Guid>("RootId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RootId");

                    b.ToTable("Registry.Registries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 219, DateTimeKind.Utc).AddTicks(8112),
                            Description = "System Root Registry",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 219, DateTimeKind.Utc).AddTicks(8129),
                            Name = "<Root>",
                            OwnerId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            RootId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("b14abcc1-39a7-4420-ac70-2b18ed73e146"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 222, DateTimeKind.Utc).AddTicks(342),
                            Description = "Module Store Registry",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 222, DateTimeKind.Utc).AddTicks(349),
                            Name = "M-Store",
                            OwnerId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            RootId = new Guid("ff44803e-e998-451f-8507-d1ecbfcbcf79"),
                            Type = 1
                        });
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Security.FileGroupPermission", b =>
                {
                    b.Property<Guid>("ObjectId");

                    b.Property<Guid>("SubjectId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("Mode");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("ObjectId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Registry.FilesGroupPermissions");
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Security.FileUserPermission", b =>
                {
                    b.Property<Guid>("ObjectId");

                    b.Property<Guid>("SubjectId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("Mode");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("ObjectId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Registry.FilesUserPermissions");
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Security.FolderGroupPermission", b =>
                {
                    b.Property<Guid>("ObjectId");

                    b.Property<Guid>("SubjectId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("Mode");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("ObjectId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Registry.FoldersGroupPermissions");

                    b.HasData(
                        new
                        {
                            ObjectId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            SubjectId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 221, DateTimeKind.Utc).AddTicks(4474),
                            IsDeleted = false,
                            Mode = 7,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 221, DateTimeKind.Utc).AddTicks(4481)
                        },
                        new
                        {
                            ObjectId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            SubjectId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 221, DateTimeKind.Utc).AddTicks(5327),
                            IsDeleted = false,
                            Mode = 7,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 221, DateTimeKind.Utc).AddTicks(5333)
                        },
                        new
                        {
                            ObjectId = new Guid("ff44803e-e998-451f-8507-d1ecbfcbcf79"),
                            SubjectId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 222, DateTimeKind.Utc).AddTicks(9034),
                            IsDeleted = false,
                            Mode = 7,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 222, DateTimeKind.Utc).AddTicks(9038)
                        },
                        new
                        {
                            ObjectId = new Guid("ff44803e-e998-451f-8507-d1ecbfcbcf79"),
                            SubjectId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 222, DateTimeKind.Utc).AddTicks(9890),
                            IsDeleted = false,
                            Mode = 7,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 222, DateTimeKind.Utc).AddTicks(9895)
                        });
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Security.FolderUserPermission", b =>
                {
                    b.Property<Guid>("ObjectId");

                    b.Property<Guid>("SubjectId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("Mode");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("ObjectId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Registry.FoldersUserPermissions");

                    b.HasData(
                        new
                        {
                            ObjectId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            SubjectId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 221, DateTimeKind.Utc).AddTicks(2079),
                            IsDeleted = false,
                            Mode = 7,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 221, DateTimeKind.Utc).AddTicks(2085)
                        },
                        new
                        {
                            ObjectId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            SubjectId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 221, DateTimeKind.Utc).AddTicks(2991),
                            IsDeleted = false,
                            Mode = 7,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 221, DateTimeKind.Utc).AddTicks(2996)
                        },
                        new
                        {
                            ObjectId = new Guid("ff44803e-e998-451f-8507-d1ecbfcbcf79"),
                            SubjectId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 222, DateTimeKind.Utc).AddTicks(7311),
                            IsDeleted = false,
                            Mode = 7,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 222, DateTimeKind.Utc).AddTicks(7316)
                        },
                        new
                        {
                            ObjectId = new Guid("ff44803e-e998-451f-8507-d1ecbfcbcf79"),
                            SubjectId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 222, DateTimeKind.Utc).AddTicks(8149),
                            IsDeleted = false,
                            Mode = 7,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 222, DateTimeKind.Utc).AddTicks(8154)
                        });
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Security.GroupPermission", b =>
                {
                    b.Property<Guid>("ObjectId");

                    b.Property<Guid>("SubjectId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("Mode");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("ObjectId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Registry.GroupPermissions");

                    b.HasData(
                        new
                        {
                            ObjectId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            SubjectId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 220, DateTimeKind.Utc).AddTicks(9624),
                            IsDeleted = false,
                            Mode = 7,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 220, DateTimeKind.Utc).AddTicks(9630)
                        },
                        new
                        {
                            ObjectId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            SubjectId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 221, DateTimeKind.Utc).AddTicks(568),
                            IsDeleted = false,
                            Mode = 7,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 221, DateTimeKind.Utc).AddTicks(573)
                        },
                        new
                        {
                            ObjectId = new Guid("b14abcc1-39a7-4420-ac70-2b18ed73e146"),
                            SubjectId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 222, DateTimeKind.Utc).AddTicks(5518),
                            IsDeleted = false,
                            Mode = 7,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 222, DateTimeKind.Utc).AddTicks(5523)
                        },
                        new
                        {
                            ObjectId = new Guid("b14abcc1-39a7-4420-ac70-2b18ed73e146"),
                            SubjectId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 222, DateTimeKind.Utc).AddTicks(6386),
                            IsDeleted = false,
                            Mode = 7,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 222, DateTimeKind.Utc).AddTicks(6391)
                        });
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Security.UserPermission", b =>
                {
                    b.Property<Guid>("ObjectId");

                    b.Property<Guid>("SubjectId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("Mode");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("ObjectId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Registry.UserPermissions");

                    b.HasData(
                        new
                        {
                            ObjectId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            SubjectId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 220, DateTimeKind.Utc).AddTicks(5011),
                            IsDeleted = false,
                            Mode = 7,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 220, DateTimeKind.Utc).AddTicks(5017)
                        },
                        new
                        {
                            ObjectId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            SubjectId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 220, DateTimeKind.Utc).AddTicks(7623),
                            IsDeleted = false,
                            Mode = 7,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 220, DateTimeKind.Utc).AddTicks(7628)
                        },
                        new
                        {
                            ObjectId = new Guid("b14abcc1-39a7-4420-ac70-2b18ed73e146"),
                            SubjectId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 222, DateTimeKind.Utc).AddTicks(3601),
                            IsDeleted = false,
                            Mode = 7,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 222, DateTimeKind.Utc).AddTicks(3606)
                        },
                        new
                        {
                            ObjectId = new Guid("b14abcc1-39a7-4420-ac70-2b18ed73e146"),
                            SubjectId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 7, 17, 6, 49, 59, 222, DateTimeKind.Utc).AddTicks(4524),
                            IsDeleted = false,
                            Mode = 7,
                            ModifiedDate = new DateTime(2019, 7, 17, 6, 49, 59, 222, DateTimeKind.Utc).AddTicks(4529)
                        });
                });

            modelBuilder.Entity("TL.Account.Data.Entities.Relationships.Subscription", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.User", "From")
                        .WithMany()
                        .HasForeignKey("FromId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TL.Api.Data.Entities.Security.Token", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");
                });

            modelBuilder.Entity("TL.Api.Data.Entities.Security.TokenLog", b =>
                {
                    b.HasOne("TL.Api.Data.Entities.Security.Token", "Token")
                        .WithMany("Logs")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Engine.Data.Entities.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Reports.Report", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Security.UserGroup", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Engine.Data.Entities.Security.User", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Security.UserRole", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Engine.Data.Entities.Security.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.System.StaticFile", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("TL.Engine.Data.Entities.System.StaticFile", "Original")
                        .WithMany("Duplicates")
                        .HasForeignKey("OriginalId");
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.System.StringVariable", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.Relationships.TgConnection", b =>
                {
                    b.HasOne("TL.Integrations.Data.Entities.Telegram.System.TgBot", "Bot")
                        .WithMany("Connections")
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Integrations.Data.Entities.Telegram.Security.TgUser", "User")
                        .WithMany("Connections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.Security.TgUser", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.Security.TgUserRole", b =>
                {
                    b.HasOne("TL.Integrations.Data.Entities.Telegram.Security.TgRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Integrations.Data.Entities.Telegram.Security.TgUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Core.File", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.System.StaticFile", "StaticFile")
                        .WithOne()
                        .HasForeignKey("TL.Registry.Data.Entities.Core.File", "FileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Registry.Data.Entities.Core.Folder", "Folder")
                        .WithMany("Files")
                        .HasForeignKey("FolderId");

                    b.HasOne("TL.Engine.Data.Entities.Security.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Core.Folder", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TL.Registry.Data.Entities.Core.Folder", "Parant")
                        .WithMany("Folders")
                        .HasForeignKey("ParantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Core.Registry", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TL.Registry.Data.Entities.Core.Folder", "Root")
                        .WithMany("Registries")
                        .HasForeignKey("RootId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Security.FileGroupPermission", b =>
                {
                    b.HasOne("TL.Registry.Data.Entities.Core.File", "Object")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Engine.Data.Entities.Security.Group", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Security.FileUserPermission", b =>
                {
                    b.HasOne("TL.Registry.Data.Entities.Core.File", "Object")
                        .WithMany("UserPermissions")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Engine.Data.Entities.Security.User", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Security.FolderGroupPermission", b =>
                {
                    b.HasOne("TL.Registry.Data.Entities.Core.Folder", "Object")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Engine.Data.Entities.Security.Group", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Security.FolderUserPermission", b =>
                {
                    b.HasOne("TL.Registry.Data.Entities.Core.Folder", "Object")
                        .WithMany("UserPermissions")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Engine.Data.Entities.Security.User", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Security.GroupPermission", b =>
                {
                    b.HasOne("TL.Registry.Data.Entities.Core.Registry", "Object")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Engine.Data.Entities.Security.Group", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Security.UserPermission", b =>
                {
                    b.HasOne("TL.Registry.Data.Entities.Core.Registry", "Object")
                        .WithMany("UserPermissions")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Engine.Data.Entities.Security.User", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
