// <auto-generated />
using System;
using ExtCore.Data.EntityFramework.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace TL.Engine.Migrations
{
    [DbContext(typeof(StorageContext))]
    [Migration("20190716223052_v1106-4")]
    partial class v11064
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TL.Account.Data.Entities.Relationships.Subscription", b =>
                {
                    b.Property<Guid>("FromId");

                    b.Property<Guid>("ToId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<bool>("Quiet");

                    b.HasKey("FromId", "ToId");

                    b.ToTable("Account.Subscriptions");

                    b.HasData(
                        new
                        {
                            FromId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            ToId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 7, 16, 22, 30, 48, 570, DateTimeKind.Utc).AddTicks(5551),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 16, 22, 30, 48, 570, DateTimeKind.Utc).AddTicks(5568),
                            Quiet = false
                        },
                        new
                        {
                            FromId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            ToId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 7, 16, 22, 30, 48, 570, DateTimeKind.Utc).AddTicks(7400),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 16, 22, 30, 48, 570, DateTimeKind.Utc).AddTicks(7409),
                            Quiet = false
                        });
                });

            modelBuilder.Entity("TL.Api.Data.Entities.Security.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<Guid?>("OwnerId");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Api.Tokens");
                });

            modelBuilder.Entity("TL.Api.Data.Entities.Security.TokenLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Method");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Parameters");

                    b.Property<int>("StatusCode");

                    b.Property<Guid>("TokenId");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("Api.TokensLogs");
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Reports.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Message");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<int?>("Priority");

                    b.Property<string>("StackTrace");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CreationDate");

                    b.HasIndex("Message");

                    b.HasIndex("ModifiedDate");

                    b.HasIndex("UserId");

                    b.ToTable("_.Reports");
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Security.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("_.Groups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 7, 16, 22, 30, 48, 538, DateTimeKind.Utc).AddTicks(9667),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 16, 22, 30, 48, 538, DateTimeKind.Utc).AddTicks(9679),
                            Name = "sa"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreationDate = new DateTime(2019, 7, 16, 22, 30, 48, 538, DateTimeKind.Utc).AddTicks(9700),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 16, 22, 30, 48, 538, DateTimeKind.Utc).AddTicks(9702),
                            Name = "all"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 7, 16, 22, 30, 48, 538, DateTimeKind.Utc).AddTicks(9708),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 16, 22, 30, 48, 538, DateTimeKind.Utc).AddTicks(9710),
                            Name = "user"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 7, 16, 22, 30, 48, 538, DateTimeKind.Utc).AddTicks(9716),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 16, 22, 30, 48, 538, DateTimeKind.Utc).AddTicks(9717),
                            Name = "system"
                        });
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Security.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("_.Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 7, 16, 22, 30, 48, 536, DateTimeKind.Utc).AddTicks(9209),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 16, 22, 30, 48, 536, DateTimeKind.Utc).AddTicks(9218),
                            Name = "sa"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 7, 16, 22, 30, 48, 536, DateTimeKind.Utc).AddTicks(9277),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 16, 22, 30, 48, 536, DateTimeKind.Utc).AddTicks(9278),
                            Name = "user"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 7, 16, 22, 30, 48, 536, DateTimeKind.Utc).AddTicks(9286),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 16, 22, 30, 48, 536, DateTimeKind.Utc).AddTicks(9288),
                            Name = "system"
                        });
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Security.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Description");

                    b.Property<bool>("IsClosed");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("LastActivity");

                    b.Property<DateTime>("LastLogon");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("Username");

                    b.Property<Guid>("WebTicket");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("_.Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 7, 16, 22, 30, 48, 517, DateTimeKind.Utc).AddTicks(4258),
                            Description = "Супер-пользователь системы TL Engine",
                            IsClosed = false,
                            IsDeleted = false,
                            LastActivity = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastLogon = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2019, 7, 16, 22, 30, 48, 517, DateTimeKind.Utc).AddTicks(4280),
                            Username = "sa",
                            WebTicket = new Guid("b8132dbd-301e-4e55-b2a2-f33c90b1988a")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 7, 16, 22, 30, 48, 517, DateTimeKind.Utc).AddTicks(6050),
                            Description = "Шаблонный пользователь системы TL Engine",
                            IsClosed = true,
                            IsDeleted = false,
                            LastActivity = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastLogon = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2019, 7, 16, 22, 30, 48, 517, DateTimeKind.Utc).AddTicks(6060),
                            Username = "user",
                            WebTicket = new Guid("e7ca0006-2c1e-4bd6-907d-120842210124")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 7, 16, 22, 30, 48, 517, DateTimeKind.Utc).AddTicks(6092),
                            Description = "Автоматика системы TL Engine",
                            IsClosed = true,
                            IsDeleted = false,
                            LastActivity = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastLogon = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2019, 7, 16, 22, 30, 48, 517, DateTimeKind.Utc).AddTicks(6093),
                            Username = "system",
                            WebTicket = new Guid("0ac89176-869e-477a-bde1-edea8ad98851")
                        });
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Security.UserGroup", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("GroupId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("_.UsersGroups");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            GroupId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreationDate = new DateTime(2019, 7, 16, 22, 30, 48, 532, DateTimeKind.Utc).AddTicks(7524),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 16, 22, 30, 48, 532, DateTimeKind.Utc).AddTicks(7543)
                        },
                        new
                        {
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            GroupId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 7, 16, 22, 30, 48, 533, DateTimeKind.Utc).AddTicks(1582),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 16, 22, 30, 48, 533, DateTimeKind.Utc).AddTicks(1590)
                        },
                        new
                        {
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            GroupId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 7, 16, 22, 30, 48, 533, DateTimeKind.Utc).AddTicks(3246),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 16, 22, 30, 48, 533, DateTimeKind.Utc).AddTicks(3248)
                        },
                        new
                        {
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            GroupId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 7, 16, 22, 30, 48, 533, DateTimeKind.Utc).AddTicks(4759),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 16, 22, 30, 48, 533, DateTimeKind.Utc).AddTicks(4760)
                        },
                        new
                        {
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            GroupId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreationDate = new DateTime(2019, 7, 16, 22, 30, 48, 533, DateTimeKind.Utc).AddTicks(9992),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 16, 22, 30, 48, 534, DateTimeKind.Utc).AddTicks(1)
                        },
                        new
                        {
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            GroupId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 7, 16, 22, 30, 48, 534, DateTimeKind.Utc).AddTicks(63),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 16, 22, 30, 48, 534, DateTimeKind.Utc).AddTicks(64)
                        },
                        new
                        {
                            UserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            GroupId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreationDate = new DateTime(2019, 7, 16, 22, 30, 48, 534, DateTimeKind.Utc).AddTicks(4254),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 16, 22, 30, 48, 534, DateTimeKind.Utc).AddTicks(4263)
                        },
                        new
                        {
                            UserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            GroupId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 7, 16, 22, 30, 48, 534, DateTimeKind.Utc).AddTicks(4318),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 16, 22, 30, 48, 534, DateTimeKind.Utc).AddTicks(4319)
                        });
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Security.UserRole", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("_.UsersRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            RoleId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 7, 16, 22, 30, 48, 527, DateTimeKind.Utc).AddTicks(8121),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 16, 22, 30, 48, 527, DateTimeKind.Utc).AddTicks(8143)
                        },
                        new
                        {
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            RoleId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 7, 16, 22, 30, 48, 528, DateTimeKind.Utc).AddTicks(2064),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 16, 22, 30, 48, 528, DateTimeKind.Utc).AddTicks(2071)
                        },
                        new
                        {
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            RoleId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 7, 16, 22, 30, 48, 528, DateTimeKind.Utc).AddTicks(3658),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 16, 22, 30, 48, 528, DateTimeKind.Utc).AddTicks(3660)
                        },
                        new
                        {
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            RoleId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 7, 16, 22, 30, 48, 528, DateTimeKind.Utc).AddTicks(7068),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 16, 22, 30, 48, 528, DateTimeKind.Utc).AddTicks(7076)
                        },
                        new
                        {
                            UserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            RoleId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 7, 16, 22, 30, 48, 528, DateTimeKind.Utc).AddTicks(9487),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 16, 22, 30, 48, 528, DateTimeKind.Utc).AddTicks(9496)
                        });
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.System.StaticFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AuthorId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<byte[]>("Data");

                    b.Property<string>("DisplayName");

                    b.Property<string>("Extension");

                    b.Property<string>("FileName");

                    b.Property<string>("FullName");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LocalPath");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<Guid?>("OriginalId");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("OriginalId");

                    b.ToTable("_.StaticFiles");
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.System.StringVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"));

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("Name");

                    b.ToTable("_.StringVariables");
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.Relationships.TgConnection", b =>
                {
                    b.Property<Guid>("BotId");

                    b.Property<Guid>("UserId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("BotId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Integrations.TgConnections");
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.Security.TgRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Integrations.TgRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 7, 16, 22, 30, 48, 607, DateTimeKind.Utc).AddTicks(5868),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 16, 22, 30, 48, 607, DateTimeKind.Utc).AddTicks(5889),
                            Name = "sa"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreationDate = new DateTime(2019, 7, 16, 22, 30, 48, 607, DateTimeKind.Utc).AddTicks(8450),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 16, 22, 30, 48, 607, DateTimeKind.Utc).AddTicks(8461),
                            Name = "admin"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 7, 16, 22, 30, 48, 607, DateTimeKind.Utc).AddTicks(9998),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 16, 22, 30, 48, 608, DateTimeKind.Utc).AddTicks(9),
                            Name = "user"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 7, 16, 22, 30, 48, 608, DateTimeKind.Utc).AddTicks(1424),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 7, 16, 22, 30, 48, 608, DateTimeKind.Utc).AddTicks(1434),
                            Name = "system"
                        });
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.Security.TgUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<int>("TgId");

                    b.Property<Guid?>("UserId");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Integrations.TgUsers");
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.Security.TgUserRole", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("Integrations.TgUsersRoles");
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.System.TgBot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AutoStart");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsRelevant");

                    b.Property<DateTime?>("LastStartDate");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("NativeName");

                    b.Property<bool>("SkipUpdates");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Token");

                    b.Property<string>("TypeName");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("Token", "TypeName")
                        .IsUnique()
                        .HasFilter("[Token] IS NOT NULL AND [TypeName] IS NOT NULL");

                    b.ToTable("Integrations.TgBots");
                });

            modelBuilder.Entity("TL.Linker.Data.Entities.Core.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<decimal>("Identifier")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("LifetimeSeconds")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(2147483647);

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasFilter("[Url] IS NOT NULL");

                    b.ToTable("Linker.Links");
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Core.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<Guid>("FileId");

                    b.Property<Guid?>("FolderId");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name");

                    b.Property<Guid>("OwnerId");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.HasIndex("FolderId");

                    b.HasIndex("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.ToTable("Registry.Files");
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Core.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name");

                    b.Property<Guid>("OwnerId");

                    b.Property<Guid?>("ParantId");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ParantId");

                    b.ToTable("Registry.Folders");
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Core.Registry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name");

                    b.Property<Guid>("OwnerId");

                    b.Property<Guid>("RootId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RootId");

                    b.ToTable("Registry.Registries");
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Security.FileGroupPermission", b =>
                {
                    b.Property<Guid>("ObjectId");

                    b.Property<Guid>("SubjectId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("Mode");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("ObjectId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Registry.FilesGroupPermissions");
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Security.FileUserPermission", b =>
                {
                    b.Property<Guid>("ObjectId");

                    b.Property<Guid>("SubjectId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("Mode");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("ObjectId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Registry.FilesUserPermissions");
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Security.FolderGroupPermission", b =>
                {
                    b.Property<Guid>("ObjectId");

                    b.Property<Guid>("SubjectId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("Mode");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("ObjectId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Registry.FoldersGroupPermissions");
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Security.FolderUserPermission", b =>
                {
                    b.Property<Guid>("ObjectId");

                    b.Property<Guid>("SubjectId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("Mode");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("ObjectId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Registry.FoldersUserPermissions");
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Security.GroupPermission", b =>
                {
                    b.Property<Guid>("ObjectId");

                    b.Property<Guid>("SubjectId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("Mode");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("ObjectId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Registry.GroupPermissions");
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Security.UserPermission", b =>
                {
                    b.Property<Guid>("ObjectId");

                    b.Property<Guid>("SubjectId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("Mode");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("ObjectId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Registry.UserPermissions");
                });

            modelBuilder.Entity("TL.Account.Data.Entities.Relationships.Subscription", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.User", "From")
                        .WithMany()
                        .HasForeignKey("FromId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TL.Api.Data.Entities.Security.Token", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");
                });

            modelBuilder.Entity("TL.Api.Data.Entities.Security.TokenLog", b =>
                {
                    b.HasOne("TL.Api.Data.Entities.Security.Token", "Token")
                        .WithMany("Logs")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Engine.Data.Entities.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Reports.Report", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Security.UserGroup", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Engine.Data.Entities.Security.User", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Security.UserRole", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Engine.Data.Entities.Security.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.System.StaticFile", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("TL.Engine.Data.Entities.System.StaticFile", "Original")
                        .WithMany("Duplicates")
                        .HasForeignKey("OriginalId");
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.System.StringVariable", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.Relationships.TgConnection", b =>
                {
                    b.HasOne("TL.Integrations.Data.Entities.Telegram.System.TgBot", "Bot")
                        .WithMany("Connections")
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Integrations.Data.Entities.Telegram.Security.TgUser", "User")
                        .WithMany("Connections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.Security.TgUser", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.Security.TgUserRole", b =>
                {
                    b.HasOne("TL.Integrations.Data.Entities.Telegram.Security.TgRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Integrations.Data.Entities.Telegram.Security.TgUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Core.File", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.System.StaticFile", "StaticFile")
                        .WithOne()
                        .HasForeignKey("TL.Registry.Data.Entities.Core.File", "FileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Registry.Data.Entities.Core.Folder", "Folder")
                        .WithMany("Files")
                        .HasForeignKey("FolderId");

                    b.HasOne("TL.Engine.Data.Entities.Security.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Core.Folder", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TL.Registry.Data.Entities.Core.Folder", "Parant")
                        .WithMany("Folders")
                        .HasForeignKey("ParantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Core.Registry", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TL.Registry.Data.Entities.Core.Folder", "Root")
                        .WithMany("Registries")
                        .HasForeignKey("RootId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Security.FileGroupPermission", b =>
                {
                    b.HasOne("TL.Registry.Data.Entities.Core.File", "Object")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Engine.Data.Entities.Security.Group", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Security.FileUserPermission", b =>
                {
                    b.HasOne("TL.Registry.Data.Entities.Core.File", "Object")
                        .WithMany("UserPermissions")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Engine.Data.Entities.Security.User", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Security.FolderGroupPermission", b =>
                {
                    b.HasOne("TL.Registry.Data.Entities.Core.Folder", "Object")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Engine.Data.Entities.Security.Group", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Security.FolderUserPermission", b =>
                {
                    b.HasOne("TL.Registry.Data.Entities.Core.Folder", "Object")
                        .WithMany("UserPermissions")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Engine.Data.Entities.Security.User", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Security.GroupPermission", b =>
                {
                    b.HasOne("TL.Registry.Data.Entities.Core.Registry", "Object")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Engine.Data.Entities.Security.Group", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TL.Registry.Data.Entities.Security.UserPermission", b =>
                {
                    b.HasOne("TL.Registry.Data.Entities.Core.Registry", "Object")
                        .WithMany("UserPermissions")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Engine.Data.Entities.Security.User", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
