// <auto-generated />
using System;
using ExtCore.Data.EntityFramework.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace TL.Engine.Migrations
{
    [DbContext(typeof(StorageContext))]
    partial class StorageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TL.Account.Data.Entities.Relationships.Subscription", b =>
                {
                    b.Property<Guid>("FromId");

                    b.Property<Guid>("ToId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<bool>("Quiet");

                    b.HasKey("FromId", "ToId");

                    b.ToTable("Account.Subscriptions");

                    b.HasData(
                        new
                        {
                            FromId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            ToId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 5, 15, 15, 55, 18, 29, DateTimeKind.Utc).AddTicks(7090),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 5, 15, 15, 55, 18, 29, DateTimeKind.Utc).AddTicks(7116),
                            Quiet = false
                        },
                        new
                        {
                            FromId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            ToId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 5, 15, 15, 55, 18, 29, DateTimeKind.Utc).AddTicks(9538),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 5, 15, 15, 55, 18, 29, DateTimeKind.Utc).AddTicks(9545),
                            Quiet = false
                        });
                });

            modelBuilder.Entity("TL.Api.Data.Entities.Security.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<Guid?>("OwnerId");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Api.Tokens");
                });

            modelBuilder.Entity("TL.Api.Data.Entities.Security.TokenLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Method");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Parameters");

                    b.Property<int>("StatusCode");

                    b.Property<Guid>("TokenId");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("Api.TokensLogs");
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Reports.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Message");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<int?>("Priority");

                    b.Property<string>("StackTrace");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CreationDate");

                    b.HasIndex("Message");

                    b.HasIndex("ModifiedDate");

                    b.HasIndex("UserId");

                    b.ToTable("_.Reports");
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Security.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("_.Groups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 5, 15, 15, 55, 18, 12, DateTimeKind.Utc).AddTicks(5947),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 5, 15, 15, 55, 18, 12, DateTimeKind.Utc).AddTicks(5965),
                            Name = "sa"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreationDate = new DateTime(2019, 5, 15, 15, 55, 18, 12, DateTimeKind.Utc).AddTicks(5997),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 5, 15, 15, 55, 18, 12, DateTimeKind.Utc).AddTicks(5998),
                            Name = "all"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 5, 15, 15, 55, 18, 12, DateTimeKind.Utc).AddTicks(6007),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 5, 15, 15, 55, 18, 12, DateTimeKind.Utc).AddTicks(6008),
                            Name = "user"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 5, 15, 15, 55, 18, 12, DateTimeKind.Utc).AddTicks(6015),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 5, 15, 15, 55, 18, 12, DateTimeKind.Utc).AddTicks(6016),
                            Name = "system"
                        });
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Security.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("_.Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 5, 15, 15, 55, 18, 10, DateTimeKind.Utc).AddTicks(7146),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 5, 15, 15, 55, 18, 10, DateTimeKind.Utc).AddTicks(7163),
                            Name = "sa"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 5, 15, 15, 55, 18, 10, DateTimeKind.Utc).AddTicks(7194),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 5, 15, 15, 55, 18, 10, DateTimeKind.Utc).AddTicks(7195),
                            Name = "user"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 5, 15, 15, 55, 18, 10, DateTimeKind.Utc).AddTicks(7204),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 5, 15, 15, 55, 18, 10, DateTimeKind.Utc).AddTicks(7206),
                            Name = "system"
                        });
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Security.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Description");

                    b.Property<bool>("IsClosed");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("LastActivity");

                    b.Property<DateTime>("LastLogon");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("Username");

                    b.Property<Guid>("WebTicket");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("_.Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 5, 15, 15, 55, 17, 999, DateTimeKind.Utc).AddTicks(7448),
                            Description = "Супер-пользователь системы TL Engine",
                            IsClosed = false,
                            IsDeleted = false,
                            LastActivity = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastLogon = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2019, 5, 15, 15, 55, 17, 999, DateTimeKind.Utc).AddTicks(7469),
                            Username = "sa",
                            WebTicket = new Guid("150913db-d129-4b02-b7b3-41e713d72630")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 5, 15, 15, 55, 17, 999, DateTimeKind.Utc).AddTicks(8558),
                            Description = "Шаблонный пользователь системы TL Engine",
                            IsClosed = true,
                            IsDeleted = false,
                            LastActivity = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastLogon = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2019, 5, 15, 15, 55, 17, 999, DateTimeKind.Utc).AddTicks(8565),
                            Username = "user",
                            WebTicket = new Guid("46a5e34b-60a0-4920-91d5-0c7e9c65d160")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 5, 15, 15, 55, 17, 999, DateTimeKind.Utc).AddTicks(8599),
                            Description = "Автоматика системы TL Engine",
                            IsClosed = true,
                            IsDeleted = false,
                            LastActivity = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastLogon = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(2019, 5, 15, 15, 55, 17, 999, DateTimeKind.Utc).AddTicks(8601),
                            Username = "system",
                            WebTicket = new Guid("b03a1e11-5639-4a67-a343-6e118280ddc5")
                        });
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Security.UserGroup", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("GroupId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("_.UsersGroups");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            GroupId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreationDate = new DateTime(2019, 5, 15, 15, 55, 18, 7, DateTimeKind.Utc).AddTicks(5425),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 5, 15, 15, 55, 18, 7, DateTimeKind.Utc).AddTicks(5445)
                        },
                        new
                        {
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            GroupId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 5, 15, 15, 55, 18, 7, DateTimeKind.Utc).AddTicks(9718),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 5, 15, 15, 55, 18, 7, DateTimeKind.Utc).AddTicks(9727)
                        },
                        new
                        {
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            GroupId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 5, 15, 15, 55, 18, 8, DateTimeKind.Utc).AddTicks(838),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 5, 15, 15, 55, 18, 8, DateTimeKind.Utc).AddTicks(839)
                        },
                        new
                        {
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            GroupId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 5, 15, 15, 55, 18, 8, DateTimeKind.Utc).AddTicks(1717),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 5, 15, 15, 55, 18, 8, DateTimeKind.Utc).AddTicks(1718)
                        },
                        new
                        {
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            GroupId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreationDate = new DateTime(2019, 5, 15, 15, 55, 18, 8, DateTimeKind.Utc).AddTicks(4436),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 5, 15, 15, 55, 18, 8, DateTimeKind.Utc).AddTicks(4442)
                        },
                        new
                        {
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            GroupId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 5, 15, 15, 55, 18, 8, DateTimeKind.Utc).AddTicks(4503),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 5, 15, 15, 55, 18, 8, DateTimeKind.Utc).AddTicks(4505)
                        },
                        new
                        {
                            UserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            GroupId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreationDate = new DateTime(2019, 5, 15, 15, 55, 18, 8, DateTimeKind.Utc).AddTicks(7091),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 5, 15, 15, 55, 18, 8, DateTimeKind.Utc).AddTicks(7101)
                        },
                        new
                        {
                            UserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            GroupId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 5, 15, 15, 55, 18, 8, DateTimeKind.Utc).AddTicks(7157),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 5, 15, 15, 55, 18, 8, DateTimeKind.Utc).AddTicks(7159)
                        });
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Security.UserRole", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("_.UsersRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            RoleId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 5, 15, 15, 55, 18, 3, DateTimeKind.Utc).AddTicks(3706),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 5, 15, 15, 55, 18, 3, DateTimeKind.Utc).AddTicks(3727)
                        },
                        new
                        {
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            RoleId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 5, 15, 15, 55, 18, 3, DateTimeKind.Utc).AddTicks(7933),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 5, 15, 15, 55, 18, 3, DateTimeKind.Utc).AddTicks(7940)
                        },
                        new
                        {
                            UserId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            RoleId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 5, 15, 15, 55, 18, 3, DateTimeKind.Utc).AddTicks(8918),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 5, 15, 15, 55, 18, 3, DateTimeKind.Utc).AddTicks(8919)
                        },
                        new
                        {
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            RoleId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 5, 15, 15, 55, 18, 4, DateTimeKind.Utc).AddTicks(1134),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 5, 15, 15, 55, 18, 4, DateTimeKind.Utc).AddTicks(1142)
                        },
                        new
                        {
                            UserId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            RoleId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 5, 15, 15, 55, 18, 4, DateTimeKind.Utc).AddTicks(3363),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 5, 15, 15, 55, 18, 4, DateTimeKind.Utc).AddTicks(3370)
                        });
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.System.StaticFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AuthorId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<byte[]>("Data");

                    b.Property<string>("DisplayName");

                    b.Property<string>("Extension");

                    b.Property<string>("FileName");

                    b.Property<string>("FullName");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LocalPath");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<Guid?>("OriginalId");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("OriginalId");

                    b.ToTable("_.StaticFiles");
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.System.StringVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"));

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("Name");

                    b.ToTable("_.StringVariables");
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.Relationships.TgConnection", b =>
                {
                    b.Property<Guid>("BotId");

                    b.Property<Guid>("UserId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("BotId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Integrations.TgConnections");
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.Security.TgRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Integrations.TgRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            CreationDate = new DateTime(2019, 5, 15, 15, 55, 18, 66, DateTimeKind.Utc).AddTicks(2449),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 5, 15, 15, 55, 18, 66, DateTimeKind.Utc).AddTicks(2476),
                            Name = "sa"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreationDate = new DateTime(2019, 5, 15, 15, 55, 18, 66, DateTimeKind.Utc).AddTicks(4982),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 5, 15, 15, 55, 18, 66, DateTimeKind.Utc).AddTicks(4991),
                            Name = "admin"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreationDate = new DateTime(2019, 5, 15, 15, 55, 18, 66, DateTimeKind.Utc).AddTicks(5868),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 5, 15, 15, 55, 18, 66, DateTimeKind.Utc).AddTicks(5875),
                            Name = "user"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreationDate = new DateTime(2019, 5, 15, 15, 55, 18, 66, DateTimeKind.Utc).AddTicks(6865),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2019, 5, 15, 15, 55, 18, 66, DateTimeKind.Utc).AddTicks(6874),
                            Name = "system"
                        });
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.Security.TgUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<int>("TgId");

                    b.Property<Guid?>("UserId");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Integrations.TgUsers");
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.Security.TgUserRole", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("Integrations.TgUsersRoles");
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.System.TgBot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AutoStart");

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsRelevant");

                    b.Property<DateTime?>("LastStartDate");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("NativeName");

                    b.Property<bool>("SkipUpdates");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Token");

                    b.Property<string>("TypeName");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("Token", "TypeName")
                        .IsUnique()
                        .HasFilter("[Token] IS NOT NULL AND [TypeName] IS NOT NULL");

                    b.ToTable("Integrations.TgBots");
                });

            modelBuilder.Entity("TL.Linker.Data.Entities.Core.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<decimal>("Identifier")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)));

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasFilter("[Url] IS NOT NULL");

                    b.ToTable("Linker.Links");
                });

            modelBuilder.Entity("TL.Account.Data.Entities.Relationships.Subscription", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.User", "From")
                        .WithMany()
                        .HasForeignKey("FromId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TL.Api.Data.Entities.Security.Token", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");
                });

            modelBuilder.Entity("TL.Api.Data.Entities.Security.TokenLog", b =>
                {
                    b.HasOne("TL.Api.Data.Entities.Security.Token", "Token")
                        .WithMany("Logs")
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Engine.Data.Entities.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Reports.Report", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Security.UserGroup", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Engine.Data.Entities.Security.User", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.Security.UserRole", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Engine.Data.Entities.Security.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.System.StaticFile", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("TL.Engine.Data.Entities.System.StaticFile", "Original")
                        .WithMany("Duplicates")
                        .HasForeignKey("OriginalId");
                });

            modelBuilder.Entity("TL.Engine.Data.Entities.System.StringVariable", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.Relationships.TgConnection", b =>
                {
                    b.HasOne("TL.Integrations.Data.Entities.Telegram.System.TgBot", "Bot")
                        .WithMany("Connections")
                        .HasForeignKey("BotId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Integrations.Data.Entities.Telegram.Security.TgUser", "User")
                        .WithMany("Connections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.Security.TgUser", b =>
                {
                    b.HasOne("TL.Engine.Data.Entities.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TL.Integrations.Data.Entities.Telegram.Security.TgUserRole", b =>
                {
                    b.HasOne("TL.Integrations.Data.Entities.Telegram.Security.TgRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TL.Integrations.Data.Entities.Telegram.Security.TgUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
