<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    <MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
    <Platforms>AnyCPU;x64</Platforms>
    <Version>1.1.0.6</Version>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>bin\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <OutputPath>bin\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>bin\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <OutputPath>bin\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Migrations\20190716223052_v1106-4.cs" />
    <Compile Remove="Migrations\20190716223052_v1106-4.Designer.cs" />
    <Compile Remove="Migrations\20190716232847_v1106-4-1.cs" />
    <Compile Remove="Migrations\20190716232847_v1106-4-1.Designer.cs" />
    <Compile Remove="Migrations\20190717065004_v1106-4-2.cs" />
    <Compile Remove="Migrations\20190717065004_v1106-4-2.Designer.cs" />
    <Compile Remove="Migrations\20190717083409_v1106-4-3.cs" />
    <Compile Remove="Migrations\20190717083409_v1106-4-3.Designer.cs" />
    <Compile Remove="Migrations\20190717123157_v1106-4.cs" />
    <Compile Remove="Migrations\20190717123157_v1106-4.Designer.cs" />
    <Compile Remove="Migrations\20190717124204_v1106-4.cs" />
    <Compile Remove="Migrations\20190717124204_v1106-4.Designer.cs" />
    <Compile Remove="Migrations\20190717124513_v1106-4.cs" />
    <Compile Remove="Migrations\20190717124513_v1106-4.Designer.cs" />
    <Compile Remove="Migrations\20190722080016_v1106-4.cs" />
    <Compile Remove="Migrations\20190722080016_v1106-4.Designer.cs" />
    <Compile Remove="Migrations\20190723123408_v1106-5-1.cs" />
    <Compile Remove="Migrations\20190723123408_v1106-5-1.Designer.cs" />
    <Compile Remove="Migrations\20190723132632_v1106-5-1.cs" />
    <Compile Remove="Migrations\20190723132632_v1106-5-1.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ExtCore.Data" Version="4.1.0" />
    <PackageReference Include="ExtCore.Data.EntityFramework" Version="4.1.0" />
    <PackageReference Include="ExtCore.Data.EntityFramework.SqlServer" Version="4.1.0" />
    <PackageReference Include="ExtCore.Mvc" Version="4.1.0" />
    <PackageReference Include="ExtCore.WebApplication" Version="4.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="2.2.6" />
    <PackageReference Include="Microsoft.Extensions.CommandLineUtils" Version="1.1.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TL.Extensions\Engine\TL.Engine.Data.Abstractions\TL.Engine.Data.Abstractions.csproj" />
    <ProjectReference Include="..\TL.Extensions\Engine\TL.Engine.Data.Entities\TL.Engine.Data.Entities.csproj" />
    <ProjectReference Include="..\TL.Extensions\Engine\TL.Engine.Data.EntityFramework\TL.Engine.Data.EntityFramework.csproj" />
    <ProjectReference Include="..\TL.Extensions\Engine\TL.Engine.Data\TL.Engine.Data.csproj" />
    <ProjectReference Include="..\TL.Extensions\Engine\TL.Engine.SDK\TL.Engine.SDK.csproj" />
    <ProjectReference Include="..\TL.Extensions\Engine\TL.Engine.Web\TL.Engine.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
