<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\..\..\TL.Engine\Extensions</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>..\..\..\TL.Engine\Extensions</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ExtCore.Mvc.Infrastructure" Version="4.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Areas\ApiHelp\Views\**;Areas\ApiHelp\Styles\**;Areas\ApiHelp\Scripts\**" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\TL.Api.Data\TL.Api.Data.csproj" />
  </ItemGroup>

</Project>
