<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\..\..\TL.Engine\Extensions\JustBot</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <OutputPath>..\..\..\TL.Engine\Extensions\JustBot</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>..\..\..\TL.Engine\Extensions\JustBot</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <OutputPath>..\..\..\TL.Engine\Extensions\JustBot</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ExtCore.Mvc.Infrastructure" Version="4.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Areas\JustBot\Views\**;Areas\JustBot\Styles\**;Areas\JustBot\Scripts\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TL.JustBot.Data\TL.JustBot.Data.csproj" />
  </ItemGroup>

</Project>
