<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <MvcRazorExcludeRefAssembliesFromPublish>false</MvcRazorExcludeRefAssembliesFromPublish>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\..\..\TL.Engine\Extensions</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>..\..\..\TL.Engine\Extensions</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ExtCore.Mvc.Infrastructure" Version="4.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Views\**;Styles\**;Scripts\**;Areas\Account\Views\**;Areas\Account\Styles\**;Areas\Account\Scripts\**" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\TL.Engine.Data\TL.Engine.Data.csproj" />
  </ItemGroup>
  
</Project>