<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
	  <UseRazorBuildServer>false</UseRazorBuildServer>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\..\TL.Engine\Extensions</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>..\..\TL.Engine\Extensions</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ExtCore.Mvc.Infrastructure" Version="4.0.0-alpha3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Areas\Account\Views\**;Areas\Account\Styles\**;Areas\Account\Scripts\**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Areas\Account\Views\**;Areas\Account\Styles\**;Areas\Account\Scripts\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Areas\Account\Views\Home\Components\SetPassword\Default.cshtml" />
    <None Remove="Areas\Account\Views\Home\Index.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TL.Account.Data\TL.Account.Data.csproj" />
    <ProjectReference Include="..\TL.Engine.SDK\TL.Engine.SDK.csproj" />
  </ItemGroup>
  
</Project>
