<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\..\..\TL.Engine\Extensions\$saferootprojectname$</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <OutputPath>..\..\..\TL.Engine\Extensions\$saferootprojectname$</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>..\..\..\TL.Engine\Extensions\$saferootprojectname$</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <OutputPath>..\..\..\TL.Engine\Extensions\$saferootprojectname$</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ExtCore.Data.Abstractions" Version="4.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TL.$saferootprojectname$.Data.Entities\TL.$saferootprojectname$.Data.Entities.csproj" />
  </ItemGroup>

</Project>
